✨ [+feature] Functionality to generate executables

diff --git a/.github/workflows/CICD_impl.yml b/.github/workflows/CICD_impl.yml
--- a/.github/workflows/CICD_impl.yml
+++ b/.github/workflows/CICD_impl.yml
@@ -155,8 +155,8 @@ jobs:
       - name: Install uv and python
         uses: astral-sh/setup-uv@v5
         with:
-          enable-cache: true
           python-version: ${{ inputs.python_package_version }}
+          enable-cache: true
 
       - name: Install Dependencies
         run: uv sync --frozen
@@ -227,8 +227,83 @@ jobs:
         run: uv run python -c "import dbrownell_BrythonWebviewTest as package; assert package.__version__ == '${{ env.PACKAGE_VERSION }}', package.__version__"
 
   # ----------------------------------------------------------------------
+  build_executables:
+    needs: package_coverage
+
+    strategy:
+      fail-fast: false
+
+      matrix:
+        include:
+          - os: ubuntu-latest
+            artifact_name: executable-linux
+            exe_name: dbrownell_BrythonWebviewTest
+
+          - os: macos-latest
+            artifact_name: executable-macos
+            exe_name: dbrownell_BrythonWebviewTest
+
+          - os: windows-latest
+            artifact_name: executable-windows
+            exe_name: dbrownell_BrythonWebviewTest.exe
+
+    name: Build Executable (${{ matrix.os }})
+    runs-on: ${{ matrix.os }}
+
+    permissions:
+      contents: read
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Install uv and python
+        uses: astral-sh/setup-uv@v5
+        with:
+          python-version: ${{ inputs.python_package_version }}
+          enable-cache: true
+
+      - name: Install Dependencies
+        run: uv sync --frozen
+
+      - name: Update Version
+        run: uv run python -m AutoGitSemVer.scripts.UpdatePythonVersion ./pyproject.toml ./src --verbose
+
+      - name: Build Executable
+        run: uv run pyinstaller src/pyinstaller.spec --noconfirm
+
+      - name: Test Executable
+        shell: bash
+        run: |
+          OUTPUT=$(./dist/${{ matrix.exe_name }} --version)
+          echo "Version output: ${OUTPUT}"
+          if [[ "0.0.0" == *"${OUTPUT}"* ]]; then
+            echo "ERROR: Unexpected output."
+            exit 1
+          fi
+
+      - name: Package Executable
+        shell: bash
+        run: |
+          cd dist
+          if [[ "${{ runner.os }}" = "Windows" ]]; then
+            7z a ../${{ matrix.artifact_name }}.zip ${{ matrix.exe_name }}
+          else
+            tar czf ../${{ matrix.artifact_name }}.tar.gz ${{ matrix.exe_name }}
+          fi
+
+      - name: Upload Executable
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.artifact_name }}
+          path: |
+            ${{ matrix.artifact_name }}.zip
+            ${{ matrix.artifact_name }}.tar.gz
+
+  # ----------------------------------------------------------------------
   release:
-    needs: [package_coverage, python_package, validate_python_package]
+    needs: [package_coverage, python_package, validate_python_package, build_executables]
 
     name: Release
     runs-on: ubuntu-latest
